# Generated by Django 4.2.4 on 2023-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_decs_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1234, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
